PackageIdentifier: PC.CleanUninstall
PackageVersion: 0.1.0
PackageLocale: en-US
Publisher: PC Tools
PublisherUrl: https://github.com/Moh-jaber/winget-pc.CleanUninstall
PublisherSupportUrl: https://github.com/Moh-jaber/winget-pc.CleanUninstall/issues
Author: PC Tools
PackageName: PC.CleanUninstall
PackageUrl: https://github.com/Moh-jaber/winget-pc.CleanUninstall
License: MIT
LicenseUrl: https://github.com/Moh-jaber/winget-pc.CleanUninstall/blob/main/LICENSE
ShortDescription: Fully uninstall Windows apps and clean leftovers.
Description: |
  PC.CleanUninstall is a portable command-line tool that removes installed applications
  and cleans leftover files, registry keys, services, and scheduled tasks. It supports
  search, deep cleaning, backups, and dry-run modes.
Moniker: pcuninstall
Tags:
  - uninstall
  - cleanup
  - registry
  - remove
  - windows
ReleaseNotesUrl: https://github.com/Moh-jaber/winget-pc.CleanUninstall/releases/tag/v0.1.0

InstallerType: portable
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Moh-jaber/winget-pc.CleanUninstall/releases/download/v0.1.0/pcuninstall.exe
    InstallerSha256: 347FCDC58BB7E8C886B79A10A7647D4339026210730AD292BE87CC83E60175BE
    Commands:
      - pcuninstall

ManifestType: singleton
ManifestVersion: 1.6.0
